# -*- coding: utf-8 -*-
"""Wspolna lista miast dla harvestera stockow."""

# (nazwa PL, slug, zapytanie ASCII, ile ujec, dodatkowe slowa-klucze do walidacji)
CITIES = [
    ("Białystok",           "bialystok",     "Bialystok",           1, ["bialystok", "białystok", "branicki"]),
    ("Ełk",                 "elk",           "Elk Poland",          1, ["elk ", " elk", "ełk", "elk,", "elku"]),
    ("Kętrzyn",             "ketrzyn",       "Ketrzyn",             1, ["ketrzyn", "kętrzyn"]),
    ("Lidzbark Warmiński",  "lidzbark",      "Lidzbark Warminski",  1, ["lidzbark"]),
    ("Łomża",          "lomza",         "Lomza",               1, ["lomza", "łomża"]),
    ("Mrągowo",             "mragowo",       "Mragowo",             1, ["mragowo", "mrągowo"]),
    ("Olsztyn",                  "olsztyn",       "Olsztyn",             1, ["olsztyn"]),
    ("Suwałki",             "suwalki",       "Suwalki",             1, ["suwalki", "suwałki"]),
    ("Ostrołęka",      "ostroleka",     "Ostroleka",           1, ["ostroleka", "ostrołęka"]),
    ("Ciechanów",           "ciechanow",     "Ciechanow",           1, ["ciechanow", "ciechanów"]),
    ("Augustów",            "augustow",      "Augustow",            1, ["augustow", "augustów"]),
    ("Iława",               "ilawa",         "Ilawa",               1, ["ilawa", "iława"]),
    ("Lublin",                   "lublin",        "Lublin",              2, ["lublin"]),
    ("Radomsko",                 "radomsko",      "Radomsko",            1, ["radomsko"]),
    ("Warszawa",                 "warszawa",      "Warsaw",              1, ["warsaw", "warszawa", "warschau"]),
    ("Grodzisk Mazowiecki",      "grodzisk",      "Grodzisk Mazowiecki", 1, ["grodzisk"]),
    ("Kraków",              "krakow",        "Krakow",              2, ["krakow", "kraków", "cracow", "krakau"]),
    ("Wrocław",             "wroclaw",       "Wroclaw",             2, ["wroclaw", "wrocław", "breslau"]),
    ("Łódź",      "lodz",          "Lodz Poland",         2, ["lodz", "łódź"]),
    ("Bydgoszcz",                "bydgoszcz",     "Bydgoszcz",           2, ["bydgoszcz"]),
    ("Katowice",                 "katowice",      "Katowice",            2, ["katowice", "spodek"]),
    ("Gdynia",                   "gdynia",        "Gdynia",              2, ["gdynia"]),
    ("Częstochowa",         "czestochowa",   "Czestochowa",         2, ["czestochowa", "częstochowa", "jasna gora", "jasna góra"]),
    ("Kielce",                   "kielce",        "Kielce",              2, ["kielce"]),
    ("Rzeszów",             "rzeszow",       "Rzeszow",             2, ["rzeszow", "rzeszów"]),
    ("Toruń",               "torun",         "Torun",               2, ["torun", "toruń"]),
    ("Bielsko-Biała",       "bielsko",       "Bielsko-Biala",       1, ["bielsko"]),
    ("Nowy Sącz",           "nowysacz",      "Nowy Sacz",           1, ["nowy sacz", "nowy sącz", "nowysacz"]),
    ("Nowy Targ",                "nowytarg",      "Nowy Targ",           1, ["nowy targ"]),
    ("Oświęcim",       "oswiecim",      "Oswiecim",            1, ["oswiecim", "oświęcim", "auschwitz"]),
    ("Żywiec",              "zywiec",        "Zywiec",              1, ["zywiec", "żywiec"]),
    ("Zakopane",                 "zakopane",      "Zakopane",            1, ["zakopane", "gubalowka", "krupowki"]),
    ("Gdańsk",              "gdansk",        "Gdansk",              1, ["gdansk", "gdańsk", "danzig"]),
]
